
name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java (JDK 17 is recommended for Flutter)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # یا جو بھی ورژن آپ کا ہے

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK (release mode)
      - name: Build release APK
        run: flutter build apk --release

      # Upload generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
