name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # یا جو بھی ورژن آپ کا ہے

      # Get dependencies
      - run: flutter pub get

      # Build release APK
      - run: flutter build apk --release

      # Upload generated APK
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
